//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeiZhi3.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WeiZhi3.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 原因 {0} : {1}. {2}\r\n是：重新请求授权；否：返回.
        /// </summary>
        internal static string AuthorizingFailedPrompt {
            get {
                return ResourceManager.GetString("AuthorizingFailedPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重新尝试一次？.
        /// </summary>
        internal static string AuthorizingFailedTitle {
            get {
                return ResourceManager.GetString("AuthorizingFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 转换失败，请直接浏览原始网页.
        /// </summary>
        internal static string ConvertingFailedPrompt {
            get {
                return ResourceManager.GetString("ConvertingFailedPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下载失败，请直接浏览原始网页.
        /// </summary>
        internal static string DownloadFailedPrompt {
            get {
                return ResourceManager.GetString("DownloadFailedPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下载....
        /// </summary>
        internal static string DownloadinPrompt {
            get {
                return ResourceManager.GetString("DownloadinPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;&lt;html scroll=&apos;no&apos;&gt;&lt;body scroll=&apos;no&apos; style=&apos;color:white&apos; bgcolor=&apos;black&apos; &gt;&lt;/body&gt;&lt;/html&gt;.
        /// </summary>
        internal static string EmptyHtml {
            get {
                return ResourceManager.GetString("EmptyHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关注 @{0}.
        /// </summary>
        internal static string FollowPrompt {
            get {
                return ResourceManager.GetString("FollowPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 格式化....
        /// </summary>
        internal static string FormattingPrompt {
            get {
                return ResourceManager.GetString("FormattingPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ReadyPrompt {
            get {
                return ResourceManager.GetString("ReadyPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 转发 @{0} 的微博.
        /// </summary>
        internal static string RetweetFailedPrompt {
            get {
                return ResourceManager.GetString("RetweetFailedPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已经转发 @{0} 的微博.
        /// </summary>
        internal static string RetweetPrompt {
            get {
                return ResourceManager.GetString("RetweetPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://t.cn/.
        /// </summary>
        internal static string ShortUrlPrefix {
            get {
                return ResourceManager.GetString("ShortUrlPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消关注 @{0}.
        /// </summary>
        internal static string UnfollowPrompt {
            get {
                return ResourceManager.GetString("UnfollowPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://weibo.com/u/.
        /// </summary>
        internal static string UserHomePrefix {
            get {
                return ResourceManager.GetString("UserHomePrefix", resourceCulture);
            }
        }
    }
}
